services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: root
      POSTGRES_DB: users
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -d users"]
        interval: 10s
        timeout: 5s
        retries: 5
